### ISSUE TITLE
cuda 11 support (?) _ZNK2at6Tensor7is_cudaEv

### ISSUE THREAD

**Issue by yosun** [Zielon/metrical-tracker#13]
(tracker) yc@razer3080ti:~/testing3dai/mica/metrical-tracker/metrical-tracker$ python tracker.py --cfg ./configs/actors/duda.yml
Traceback (most recent call last):
  File "tracker.py", line 31, in <module>
    from pytorch3d.io import load_obj
  File "/home/yc/anaconda3/lib/python3.7/site-packages/pytorch3d/io/__init__.py", line 4, in <module>
    from .obj_io import load_obj, load_objs_as_meshes, save_obj
  File "/home/yc/anaconda3/lib/python3.7/site-packages/pytorch3d/io/obj_io.py", line 14, in <module>
    from pytorch3d.renderer import TexturesAtlas, TexturesUV
  File "/home/yc/anaconda3/lib/python3.7/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/yc/anaconda3/lib/python3.7/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: /home/yc/anaconda3/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv

**Comment by Zielon** [comment]
I seems that your pytorch has different version. I would try fresh install of the env.

**Comment by yosun** [comment]
Yes, this was from a fresh install of the env.
