### ISSUE TITLE
zipfile.BadZipFile: Bad CRC-32 for file 'tex_dir.npy'

### ISSUE THREAD

**Issue by kikiwxalynika** [Zielon/metrical-tracker#37]
When I try to run python tracker.py --cfg ./configs/actors/duda.yml, I met error like :
Traceback (most recent call last):
  File "/root/autodl-fs/tracker_hjh/tracker.py", line 764, in <module>
    ff = Tracker(config, device='cuda:0')
  File "/root/autodl-fs/tracker_hjh/tracker.py", line 104, in __init__
    self.setup_renderer()
  File "/root/autodl-fs/tracker_hjh/tracker.py", line 121, in setup_renderer
    self.flametex = FLAMETex(self.config).to(self.device)
  File "/root/autodl-fs/tracker_hjh/flame/FLAME.py", line 294, in __init__
    texture_basis = tex_space[pc_key].reshape(-1, n_pc)
  File "/root/miniconda3/envs/tracker/lib/python3.9/site-packages/numpy/lib/npyio.py", line 253, in __getitem__
    return format.read_array(bytes,
  File "/root/miniconda3/envs/tracker/lib/python3.9/site-packages/numpy/lib/format.py", line 812, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "/root/miniconda3/envs/tracker/lib/python3.9/site-packages/numpy/lib/format.py", line 947, in _read_bytes
    r = fp.read(size - len(data))
  File "/root/miniconda3/envs/tracker/lib/python3.9/zipfile.py", line 924, in read
    data = self._read1(n)
  File "/root/miniconda3/envs/tracker/lib/python3.9/zipfile.py", line 1014, in _read1
    self._update_crc(data)
  File "/root/miniconda3/envs/tracker/lib/python3.9/zipfile.py", line 942, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'tex_dir.npy'
How can I fix this error? And what is ’tex_dir.npy'? Thanks!

**Comment by sword4869** [comment]
Files in `data` are corrupted, redownload or recopy can fix it
